name: Generate output files

on:
  push:
    tags:
    - v*

permissions:
  contents: write

jobs:
  # Generate-local:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: kicad/kicad:$KICAD_TAG
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4

  Generate-demo:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:nightly-full
      options: --user root
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate files
      run: |
        cp -r /usr/share/kicad/demos/video ./video
        cd video
        kicad-cli jobset run --file ../jlcpcb.kicad_jobset video.kicad_pro

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: *.zip
